version: '3.9'

services:
  app:
    build: .
    ports:
      - "8081:8081"  # Change port from 8080 to 8081
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: lockyer
      DB_USER: lockyer
      DB_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
    command: ["java", "-jar", "financial-java-api-3.1.3-SNAPSHOT.jar", "--spring.profiles.active=dev", "--spring.datasource.username=lockyer", "--spring.datasource.password=password"]

  db:
    image: postgres:15
    platform: linux/arm64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lockyer
      POSTGRES_USER: lockyer
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
