version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: financial
      POSTGRES_USER: lockyer
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - finnet

  app:
    image: eclipse-temurin:17-jdk
    container_name: financial-api
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      sh -c "echo 'Waiting for db...';
      sleep 10;
      java -jar financial-java-api-3.1.3-SNAPSHOT.jar
      --server.port=8081
      --spring.profiles.active=dev
      --spring.datasource.url=jdbc:postgresql://db:5432/financial
      --spring.datasource.username=lockyer
      --spring.datasource.password=password"
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - finnet

networks:
  finnet:
